owner: artistxoder
repo: artistxoder.github.io

sites:
  - name: ArtistXoder Website
    url: https://artistxoder.com/
  - name: 

status-website:
  name: System Status
  baseUrl: /
  cname: status.artistxoder.com
