owner: artistxoder
repo: artistxoder.github.io

sites:
  - name: ArtistXoder Website
    url: https://artistxoder.com/

  - name: Minecraft Bedrock Server
    check: icmp-ping
    url: mc.artistxoder.com
    icon: https://raw.githubusercontent.com/PolyhedralDev/Terraform/master/assets/icon.png

status-website:
  name: System Status
  baseUrl: /
  cname: status.artistxoder.com
